services:

  mysql:
    build:
      context: ./mysql-db
      dockerfile: Dockerfile

    container_name: tourism-mysql

    restart: unless-stopped

    env_file:
      - ./mysql-db/.env

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - tourism-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "tourism_user", "-ptourism123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: tourism-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - tourism-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: tourism-frontend

    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      - backend

    networks:
      - tourism-network


volumes:
  mysql_data:


networks:
  tourism-network:
    driver: bridge