from pathlib import Path

from ml.domestic.preprocess import Domestic_Preprocessor
from ml.domestic.feature_engineering import FeatureEngineer
from ml.domestic.vectorizer import Vectorizer


# Keep sibling imports working when running from repo root or from this folder.
# These scripts rely on relative paths built with pathlib, so working directory is irrelevant.



class Domestic_recommendation_pipeline:

    def __init__(self):
        base_dir = Path(__file__).resolve().parent
        dataset_dir = base_dir / "dataset"
        # Use the CSVs that actually exist in this repo.
        self.raw_dataset = str(dataset_dir / "Domestic-Indian Packages.csv")

        # These are outputs generated by the pipeline itself.
        processed_dir = base_dir / "data"
        self.cleaned_dataset = str(processed_dir / "domestic_cleaned.csv")
        self.training_dataset = str(processed_dir / "domestic_training.csv")


    def run(self):

        print("=" * 60)
        print("Step 1 : Data Preprocessing")
        print("=" * 60)

        Domestic_Preprocessor(
            self.raw_dataset,
            self.cleaned_dataset
        ).process()

        print()

        print("=" * 60)
        print("Step 2 : Feature Engineering")
        print("=" * 60)

        FeatureEngineer(
            self.cleaned_dataset,
            self.training_dataset
        ).process()

        print()

        print("=" * 60)
        print("Step 3 : Building Recommendation Model")
        print("=" * 60)

        Vectorizer(self.training_dataset).process()

        print()

        print("=" * 60)
        print("Domestic Model Generated Successfully")
        print("=" * 60)


if __name__ == "__main__":

    Domestic_recommendation_pipeline().run()